echo 'START PROGRAM I BAKGRUNNEN'
echo '[program] & '
echo 'VIKTIG: HUSK MELLOMROM ETTER &-TEGN'
echo ''
echo ''

echo 'mv: flytt fil (brukes også for å gi nytt navn til fil)'
echo ''
echo 'cp: kopier fil'
echo 'cp -R: kopier mappe'
echo ''
echo 'rm: slett fil'
echo 'rm -rf: slett mappe'
echo ''
echo 'ls -l: list mappeinnhold BEDRE!!!!'
echo ''
echo '[kommando] | less: print output fra [kommando] til lesbart vindu'
echo ''
echo ''

echo 'Ctrl+C for å (tvinge) avslutte program'
echo ''
echo 'BYOBU: Ctrl+A, [slipp fingeren din av det svartens tastaturet], D: Detach fra byobu-vindu'
echo ''
echo 'BYOBU: Ctrl+Shift+F2: Lag nytt byobu-vindu [bak det sabla vinduet du er i nå]'
echo 'BYOBU: Alt+Pil Opp/Pil Ned: Hopp mellom byobu-vinduer'
echo ''
echo ''
echo 'BYOBU: Shift+F2: Lag vertikal ekstravindu i byobu'
echo 'BYOBU: Shift+Pil [Retning]: hopp mellom splitta vinduer i byobu'

